---
# ===========================================
# Ubuntu-specific Variables
# ===========================================

php_version: "8.3"

docker_gpg_key: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
