---
# Docker role default variables

docker_package_state: present
docker_service_state: started
docker_service_enabled: true

# Docker Compose
docker_compose_version: "v2.24.5"
docker_compose_path: /usr/local/bin/docker-compose

# Docker daemon options
docker_iptables_fix: true
docker_log_driver: json-file
docker_log_max_size: "10m"
docker_log_max_file: "3"
docker_storage_driver: overlay2
