---
all:
  children:
    vps:
      hosts:
        # Add your VPS here
        # production:
        #   ansible_host: 1.2.3.4
        #   ansible_user: root
        #   ansible_ssh_private_key_file: ~/.ssh/id_rsa

    debian:
      children:
        vps:

    ubuntu:
      children:
        vps:
