---
# UFW Firewall Configuration

- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Reset UFW to defaults
  community.general.ufw:
    state: reset
  when: ufw_reset | default(false)

- name: Set default incoming policy
  community.general.ufw:
    direction: incoming
    policy: "{{ ufw_default_policies.incoming }}"

- name: Set default outgoing policy
  community.general.ufw:
    direction: outgoing
    policy: "{{ ufw_default_policies.outgoing }}"

- name: Set default routed policy
  community.general.ufw:
    direction: routed
    policy: "{{ ufw_default_policies.routed }}"

- name: Enable logging
  community.general.ufw:
    logging: "{{ ufw_logging }}"

- name: Allow SSH port
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
    comment: SSH

- name: Allow configured ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_allowed_ports | difference([ssh_port]) }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Ensure UFW starts on boot
  ansible.builtin.lineinfile:
    dest: /etc/ufw/ufw.conf
    regexp: '^ENABLED='
    line: 'ENABLED=yes'
    state: present
